### ISSUE TITLE
The location of e2e script

### ISSUE THREAD

**Issue by Hzfengsy** [Hzfengsy/relax#1]
TBD

**Comment by jinhongyii** [comment]
e2e resnet: tests/python/relax_e2e/test_resnet.py

**Comment by MasterJH5574** [comment]
Let's refer to this script for end-to-end tuning and remote measurement!

https://github.com/Hzfengsy/relax/blob/0ea51f34a0b2ced1101f109b10c39223b3c8d47c/tests/python/relax/e2e_autotir.py#L151-L236
